### PR TITLE
Changes to block, limit thermal spam, and make a default TCP congestion tweak

### PR DESCRIPTION
**Pull request by EyeCantCU**
According to Sultan, CFQ exposes an ongoing bug in the MMC driver for Onyx and Bacon through VFS. Unfortunately, this leads to instability whenever it is enabled.

I have disabled it in the defconfig, but as somewhat of a solution I added BFQ with idle slice disabled, and while it does not do as well as CFQ with normal workloads, it gets the job done, and CM seems to favor it a lot. It works really well for multitasking.

I also added Zen at the request of a user as it is based on VR with several tweaks that make it FCFS, and really optimal when it comes to IO throughput thus I made it default. Through testing, it works better than NOOP was previously doing while being better tuned for performance. We don't want IO to be liited in CPU cycles, especially during boot.

Deadline is also FIFO now, and ROW has been optimized.

As sort of a side thing, I noticed we were using Cubic for TCP congestion which is Linux's default, but Westwood performs better over all so I think it is best we use it instead

I think that's all I missed ;)

Just came across a patch from motorola that removes the spam from the thermal driver at lower thresholds too

### CODE REVIEW

**Comment by franciscofranco** [comment]
I can't accept this PR as it is. I don't want ZEN and ROW's "magic values". In fact I'll be disabling ROW soon since it also exposes bugs in the MMC subsystem. I don't mind adding BFQ since it's pretty much accepted everywhere else and in some Linux distributions. I also don't want myfluxi's patch for deadline values, I prefer other values.

The patch from Motorola doesn't seem like it's the original one, since the one you merged is actually introducing the spam with pr_info().

**Comment by EyeCantCU** [comment]
Okay. I'll fix everything up. What about the deadline patch that allows for 0ms latency?

**Comment by franciscofranco** [comment]
That's fine I think it was merged upstream.

**Comment by EyeCantCU** [comment]
Ready to be merged now @franciscofranco

**Pull request merged**
