### PR TITLE
Fix simple ondemand, and display driver

### PR DESCRIPTION
**Pull request by EyeCantCU**
WIP. Do not merge yet. I'll let you know when this is ready

1. Fix simple ondemand from crashing as well as bring it up to spec
2. Fix kernel panic caused by our display driver

### CODE REVIEW

**Comment by CertifiedBlyndGuy** [comment]
Oh, and one more thing. In the defconfig, F2FS needs to have its options updated to look like this:

CONFIG_F2FS_FS=y
CONFIG_F2FS_STAT_FS=y
CONFIG_F2FS_FS_XATTR=y
CONFIG_F2FS_FS_POSIX_ACL=y 
CONFIG_F2FS_FS_SECURITY=y
# CONFIG_F2FS_CHECK_FS is not set
# CONFIG_F2FS_IO_TRACE is not set

**Comment by EyeCantCU** [comment]
I removed the F2FS stuff as it probably isn't optimal to make changes to fstab in order to make it work. Support in the future would be nice though. I am working on the display driver right now, and I will let you know when I have finished

**Comment by franciscofranco** [comment]
Interesting. I did not know about the crash on the s3508 driver. Thanks for the simple_ondemand fixes. Let me know when you finish this so I can merge.

**Comment by EyeCantCU** [comment]
@franciscofranco 

I hate to bother, but could you push your defconfig when you get a chance?

**Comment by franciscofranco** [comment]
https://github.com/franciscofranco/onyx/commit/93a251671db5560e765ad1144b025401026f31ea

**Comment by EyeCantCU** [comment]
Oh lol. Well... I am blind

**Comment by franciscofranco** [comment]
I just pushed it.

**Comment by EyeCantCU** [comment]
Okay. I think I'm going to close this for the time being until I find out why we need that revert. I'll take a diff between the display driver in OOS 2 (which almost all kernels still use oddly enough) and the driver used in OOS 3. We shouldn't need that revert, and I'm going to try and trace the issue accordingly. Thanks for pushing the config. I thought I had missed it when going over the kernel sources

**Comment by franciscofranco** [comment]
Why did you close this? There was some interesting patches here that I could merge.

**Comment by EyeCantCU** [comment]
I'm going to reopen it in a moment. I fixed the display driver causing a kernel panic on resume. I didn't want to leave it the way it was.

**Comment by EyeCantCU** [comment]
@franciscofranco https://github.com/franciscofranco/onyx/pull/3

**Pull request closed without merging**
