### PR TITLE
Do Not Merge/WIP: Changes in preparation for Lineage

### PR DESCRIPTION
**Pull request by EyeCantCU**
Instead of completely rebasing the kernel, I thought that it may just be best to update the one we have. This is not by any means ready, but you might find some of it useful on M. I think I missed a few things, but the basic stuff is there

### CODE REVIEW

**Comment by franciscofranco** [comment]
This needs to be in a different branch, I can't merge the prima drivers on stock. Let me create the branch for you and you can rebase all of this on the branch if it's not a problem for you.

**Comment by franciscofranco** [comment]
Created branch nougat.

**Comment by EyeCantCU** [comment]
Okay. Awesome. I'll start work on it

**Comment by EyeCantCU** [comment]
https://github.com/franciscofranco/onyx/pull/6

**Pull request closed without merging**
